version: "3.3"
services:
  db:
    image: mysql:8.0
    container_name : wordpress_mysql
    volumes :
      - "./volumes/mysql/data:/var/lib/mysql"
      - "./volumes/mysql/backup:/data/backups"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:6.2.0-php8.0-fpm
    container_name : wordpress
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_PHP_MEMORY_LIMIT: 512
    volumes:
      - ./wordpress:/var/www/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini:ro

  nginx:
    image: nginx:1.20.2
    container_name : wordpress_nginx
    depends_on:
      - wordpress
    ports:
      - "8050:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wordpress:/var/www/html